export const ExpenseData = [
  {
    id: 1,
    paid: false,
    expense: "Paper Towel Touchless",
    monthlyValue: 55,
    date: "3/28/2023",
    installments: 1,
    totalValue: 65,
    description:
      "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
    userId: "0290542c-4954-4e87-aa8b-b300d9089a2c",
  },
  {
    id: 2,
    paid: true,
    expense: "Yeast Dry - Fleischman",
    monthlyValue: 47,
    date: "6/21/2023",
    installments: 2,
    totalValue: 1,
    description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    userId: "e67cb4e4-1732-4d59-b41a-f0f930a2bb59",
  },
  {
    id: 3,
    paid: true,
    expense: "Pasta - Spaghetti, Dry",
    monthlyValue: 95,
    date: "5/18/2023",
    installments: 3,
    totalValue: 67,
    description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    userId: "001e4291-3f5e-4065-b2c5-e1d6bf414a13",
  },
  {
    id: 4,
    paid: true,
    expense: "Pepper - Roasted Red",
    monthlyValue: 42,
    date: "7/24/2023",
    installments: 4,
    totalValue: 43,
    description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    userId: "e08f6464-b76e-4ce1-b1a6-89c2578693bf",
  },
  {
    id: 5,
    paid: false,
    expense: "Whmis - Spray Bottle Trigger",
    monthlyValue: 62,
    date: "10/17/2023",
    installments: 5,
    totalValue: 51,
    description:
      "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    userId: "b7bb2fca-4d8a-4674-83ae-4a38a7f5adff",
  },
  {
    id: 6,
    paid: true,
    expense: "Brandy - Bar",
    monthlyValue: 54,
    date: "7/30/2023",
    installments: 6,
    totalValue: 66,
    description:
      "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
    userId: "d0a473d6-7f43-4629-b99d-33e99c30e0ff",
  },
  {
    id: 7,
    paid: false,
    expense: "Juice - Orange",
    monthlyValue: 31,
    date: "8/27/2023",
    installments: 7,
    totalValue: 96,
    description:
      "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    userId: "cfa6fc73-016b-4b82-8ab7-76ca8998b98b",
  },
  {
    id: 8,
    paid: false,
    expense: "Soup - Knorr, Veg / Beef",
    monthlyValue: 97,
    date: "12/29/2022",
    installments: 8,
    totalValue: 8,
    description:
      "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    userId: "4a659218-21e1-48c0-9404-c4e16f6efe28",
  },
  {
    id: 9,
    paid: true,
    expense: "Beef - Ox Tail, Frozen",
    monthlyValue: 5,
    date: "4/4/2023",
    installments: 9,
    totalValue: 7,
    description:
      "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    userId: "a4a7d250-70a0-46bf-a3f8-293209e169ae",
  },
  {
    id: 10,
    paid: true,
    expense: "Anchovy Fillets",
    monthlyValue: 92,
    date: "8/4/2023",
    installments: 10,
    totalValue: 2,
    description:
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    userId: "eaefdec9-8063-4520-81e1-7bd9da693f22",
  },
  {
    id: 11,
    paid: true,
    expense: "Wine - German Riesling",
    monthlyValue: 63,
    date: "9/26/2023",
    installments: 11,
    totalValue: 57,
    description:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    userId: "ee27f43f-a9fa-4e63-b22d-10d1c75a2032",
  },
  {
    id: 12,
    paid: true,
    expense: "Cheese - Valancey",
    monthlyValue: 23,
    date: "3/25/2023",
    installments: 12,
    totalValue: 1,
    description:
      "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    userId: "e5fde867-3585-4ede-9fee-0f16fc067d96",
  },
  {
    id: 13,
    paid: false,
    expense: "Coffee - Irish Cream",
    monthlyValue: 79,
    date: "1/25/2023",
    installments: 13,
    totalValue: 77,
    description:
      "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    userId: "19364e0e-89ba-4e55-9e5a-ab75966898d1",
  },
  {
    id: 14,
    paid: false,
    expense: "Cheese - Comtomme",
    monthlyValue: 37,
    date: "11/1/2022",
    installments: 14,
    totalValue: 19,
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    userId: "7ea193a2-3fb5-46a3-9497-3128b41e79d6",
  },
  {
    id: 15,
    paid: false,
    expense: "Beans - Navy, Dry",
    monthlyValue: 38,
    date: "10/4/2023",
    installments: 15,
    totalValue: 86,
    description:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    userId: "1acb13af-9896-49ba-8d04-fe527d220ac5",
  },
  {
    id: 16,
    paid: true,
    expense: "Sugar - Invert",
    monthlyValue: 57,
    date: "10/20/2023",
    installments: 16,
    totalValue: 13,
    description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    userId: "82801277-e3ce-47c2-9500-d2e2257a7258",
  },
  {
    id: 17,
    paid: false,
    expense: "Kahlua",
    monthlyValue: 70,
    date: "7/9/2023",
    installments: 17,
    totalValue: 9,
    description:
      "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    userId: "1d9ab286-d4ec-4766-97bc-605f9ae90b82",
  },
  {
    id: 18,
    paid: true,
    expense: "Bread Foccacia Whole",
    monthlyValue: 82,
    date: "8/31/2023",
    installments: 18,
    totalValue: 20,
    description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    userId: "586dc486-2be7-41a1-964a-48057748ee20",
  },
  {
    id: 19,
    paid: false,
    expense: "Triple Sec - Mcguinness",
    monthlyValue: 21,
    date: "8/30/2023",
    installments: 19,
    totalValue: 3,
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    userId: "46e9c34e-8f16-4e26-b42e-619a604b06b4",
  },
  {
    id: 20,
    paid: true,
    expense: "Tart Shells - Savory, 4",
    monthlyValue: 17,
    date: "9/21/2023",
    installments: 20,
    totalValue: 9,
    description:
      "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.",
    userId: "9bcdc8ed-7e89-4fff-a4e8-b1fbdece265d",
  },
  {
    id: 21,
    paid: true,
    expense: "Coffee Cup 12oz 5342cd",
    monthlyValue: 80,
    date: "3/28/2023",
    installments: 21,
    totalValue: 3,
    description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
    userId: "f31c6128-ecaf-4343-a075-bfe39edade1f",
  },
  {
    id: 22,
    paid: true,
    expense: "Oneshot Automatic Soap System",
    monthlyValue: 61,
    date: "5/6/2023",
    installments: 22,
    totalValue: 80,
    description:
      "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    userId: "44cfe7ad-8c12-4a4b-99e0-d16cf333826d",
  },
  {
    id: 23,
    paid: false,
    expense: "Tart - Butter Plain Squares",
    monthlyValue: 58,
    date: "9/21/2023",
    installments: 23,
    totalValue: 28,
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    userId: "c6e28e4e-4bb9-4060-853a-0fb32868889e",
  },
  {
    id: 24,
    paid: false,
    expense: "Wine - Shiraz South Eastern",
    monthlyValue: 52,
    date: "5/16/2023",
    installments: 24,
    totalValue: 61,
    description:
      "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
    userId: "7a089c6a-8482-4eb7-944b-622a4a8b1b75",
  },
  {
    id: 25,
    paid: false,
    expense: "Sole - Dover, Whole, Fresh",
    monthlyValue: 59,
    date: "8/25/2023",
    installments: 25,
    totalValue: 10,
    description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    userId: "e4f5ddb8-9d8b-41f6-bd8b-239125a97fca",
  },
  {
    id: 26,
    paid: true,
    expense: "Yogurt - French Vanilla",
    monthlyValue: 11,
    date: "9/22/2023",
    installments: 26,
    totalValue: 83,
    description:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.",
    userId: "c10e4bb8-c1ea-4d61-9b87-d5d9d50781ec",
  },
  {
    id: 27,
    paid: true,
    expense: "Wine - Cave Springs Dry Riesling",
    monthlyValue: 68,
    date: "10/13/2023",
    installments: 27,
    totalValue: 94,
    description: "Fusce consequat. Nulla nisl. Nunc nisl.",
    userId: "59190a54-612f-46e8-87d4-8468745f610d",
  },
  {
    id: 28,
    paid: true,
    expense: "Lamb Tenderloin Nz Fr",
    monthlyValue: 54,
    date: "5/18/2023",
    installments: 28,
    totalValue: 80,
    description:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    userId: "1aef27b6-32f7-4d67-a129-057573214621",
  },
  {
    id: 29,
    paid: true,
    expense: "Alize Red Passion",
    monthlyValue: 5,
    date: "4/13/2023",
    installments: 29,
    totalValue: 70,
    description:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
    userId: "05436e53-3f2a-4f6f-94e0-21815bdf116d",
  },
  {
    id: 30,
    paid: false,
    expense: "Lemonade - Kiwi, 591 Ml",
    monthlyValue: 48,
    date: "1/14/2023",
    installments: 30,
    totalValue: 100,
    description:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    userId: "3b334f80-43ec-4efb-9d27-65a225090838",
  },
];

export type Expense = (typeof ExpenseData)[number];
